module.exports = {
  POST_METHOD: 'POST',
  RPC_VERSION: '1.0',
  CONTENT_TYPE: 'text/plain',
  RPC_ID: `Keychain-${Date.now()}`,
  FEE_PER_BYTE: 2,
  WEIGHTED_INPUT: 148,
  WEIGHTED_OUTPUT: 34,
  BTC_DUST: 0.00000546,
  NO_OF_TX_OUTPUTS: 3,
  FINAL_NO_OF_TX_OUTPUTS: 2,
  FINAL_NO_OF_TX_INPUTS: 1,
  ETH_DID_CREATE: 'create',
  ETH_DID_UPDATE: 'update',
  ETH_DID_TRANSFER: 'transfer',
  ETH_DID_DELETE: 'delete',
  HTTPS: 'https',
  DID_DOC_URL_REGEX:
    '^(https?://)?(www\\.)?([-a-z0-9]{1,63}\\.)*?[a-z0-9][-a-z0-9]{0,61}[a-z0-9]\\.[a-z]{2,6}(/[-\\w@\\+\\.~#\\?&/=%]*)?$',
  SECP256K1: 'EcdsaSecp256k1VerificationKey2019',

  BTC_BLOCKCHAIN: 'btc',
  ETH_BLOCKCHAIN: 'eth',
  OMNI_BLOCKCHAIN: 'omni',
  IPFS: 'ipfs',
  TESTNET: 'testnet',
  OMNI_TRANSACTION_TYPES: {
    incoming: 'incoming',
    outgoing: 'outgoing',
  },
  W3C_DID_SCHEMA: 'https://www.w3.org/ns/did/v1',
  ALLOWED_CHAINS: ['btc', 'eth', 'omni'],
  SUPPORTED_LOCALES: ['en'],
  DEFAULT_LOCALE: 'en',
  IMAGE_EXT_LIST: [
    '.gif',
    '.jpeg',
    '.jpg',
    '.png',
    '.svg',
    '.tif',
    '.tiff',
    '.webp',
  ],
  VIDEO_EXT_LIST: ['.avi', '.mp4', '.mpeg', '.ogv', '.ts', '.webm'],
  AUDIO_EXT_LIST: [
    '.aac',
    '.mid',
    '.midi',
    '.mp3',
    '.oga',
    '.opus',
    '.wav',
    '.weba',
  ],
  FB_FEE_RATE: 0.00011,
  TO_SATOSHI: 1e8,
};
