module.exports = {
  POST_METHOD: 'POST',
  RPC_VERSION: '1.0',
  CONTENT_TYPE: 'text/plain',
  RPC_ID: 'someRPCId',
  FEE_PER_BYTE: 2,
  WEIGHTED_INPUT: 148,
  WEIGHTED_OUTPUT: 34,
  BTC_DUST: 0.00000546,
  NO_OF_TX_OUTPUTS: 3,
  FINAL_NO_OF_TX_OUTPUTS: 2,
  FINAL_NO_OF_TX_INPUTS: 1,
  ETH_DID_CREATE: 'create',
  ETH_DID_UPDATE: 'update',
  ETH_DID_TRANSFER: 'transfer',
  ETH_DID_DELETE: 'delete',
  HTTPS: 'https',
};
